function counts = generate_gaze_spikes(conf, do_save)

if ( nargin < 2 )
  do_save = true;
end

if ( nargin < 1 )
  conf = bfw.config.load();
end

counts = bfw_gather_spikes_and_rng( ...
    'spike_func', 'spike_counts' ...
  , 'look_back', -1 ...
  , 'look_ahead', 1 ...
  , 'window_size', 0.05 ...
  , 'step_size', 0.05 ...
  , 'rois', {'eyes_nf', 'face', 'right_nonsocial_object'} ...
  , 'spike_dir', 'cc_spikes' ...
  , 'events_subdir', 'raw_events' ...
  , 'is_already_non_overlapping', true ...
  , 'collapse_nonsocial_object_rois', false ...
  , 'config', conf ...
  , 'include_rng', false ...
);

if ( do_save )
  save_p = fullfile( bfw.dataroot(conf), 'analyses/spike_lda/only_gaze_spikes' );
  save( fullfile(save_p, 'gaze_counts.mat'), 'counts' );
end

end