%%

reward_counts = bfw_get_cs_reward_response( ...
    'event_names', {'cs_target_acquire', 'cs_delay', 'cs_reward', 'iti', 'fixation'} ...
  , 'look_back', -0.5 ...
  , 'look_ahead', 1.5 ...
  , 'is_firing_rate', false ...
  , 'include_rasters', false ...
);

%%

bfw_lda.run_cs_reward_level_modulation_anova( reward_counts ...
  , 'base_subdir', '5_trials_per_condition/' ...
);