reward_counts = bfw_get_cs_reward_response( ...
    'event_names', {'cs_presentation', 'fixation', 'iti'} ...
  , 'look_back', -0.2 ...
  , 'look_ahead', 1 ...
  , 'is_firing_rate', false ...
  , 'include_rasters', false ...
);

%%

base_event = 'iti';

switch ( base_event )
  case 'fixation'
    base_t = [0, 0.15];
    base_subdir = 'fixation_baseline';
  case 'iti'
    base_t = [0.5, 1];
    base_subdir = 'iti_baseline';
  otherwise
    error( 'unrecognized event' );
end

bfw_lda.cs_reward_level_modulation_anova( ...
  'reward_counts', reward_counts ...
  , 'base_event', base_event ...
  , 'base_t', base_t ...
  , 'do_save', true ...
  , 'base_subdir', base_subdir ...
  , 'lda_rng_seed', 0 ...
)