reward_counts = bfw_get_cs_reward_response( ...
    'event_names', {'cs_reward', 'cs_presentation'} ...
  , 'look_back', -0.2 ...
  , 'look_ahead', 1.5 ...
  , 'is_firing_rate', true ...
  , 'include_rasters', true ...
);

%%

bfw_lda.plot_cs_psth( reward_counts ...
  , 'do_save', true ...
  , 'base_subdir', 'no-errorbar' ...
);