function run_plot_sumarize_behavior(varargin)

defaults = bfw.get_common_make_defaults();
defaults.config = bfw_st.default_config();

params = bfw.parsestruct( defaults, varargin );
conf = params.config;

% isi_quantile_edges = { [7.5, 10], [10, 15], [6, 7] };
isi_quantile_edges = { [15, 25] };

for i = 1:numel(isi_quantile_edges)
  
shared_utils.general.progress( i, numel(isi_quantile_edges) );
  
current_edges = isi_quantile_edges{i};

%%

fix_info_outs = bfw_st.fix_info( ...
  'config', conf ...
  , 'is_parallel', true ...
  , 'stim_isi_quantile_edges', current_edges ...
);

%%

decay_outs = bfw_st.stim_fixation_decay( ...
  'config', conf ...
  , 'rois', {'eyes_nf', 'face'} ...
  , 'stim_isi_quantile_edges', current_edges ...
);

%%

base_subdir = sprintf( 'isi_%0.2f-%0.2f/', current_edges(1), current_edges(2) );

bfw_st.summarize_fix_info( ...
  'fix_info_outs', fix_info_outs ...
  , 'overlay_points', true ...
  , 'do_save', true ...
  , 'base_mask_func', @(labels, mask) find(labels, 'previous_sham', mask) ...
  , 'points_are', 'session' ...
  , 'base_subdir', base_subdir ...
);

%%

bfw_st.summarize_decay_curve( ...
    'decay_outs', decay_outs ...
  , 'do_save', true ...
  , 'base_subdir', base_subdir ...
);

end