%%  Bounds file based.

rois = { 'eyes_nf', 'face', 'left_nonsocial_object', 'right_nonsocial_object', 'everywhere' };

bfw_make_raw_recording_events( ...
    'save', true ...
  , 'append', false ...
  , 'skip_existing', false ...
  , 'samples_subdir', 'aligned_raw_samples' ...
  , 'use_bounds_file_for_rois', true ...
  , 'check_accept_mutual_event_func', @bfw.default_check_accept_mutual_event_func ...
  , 'duration', 10 ...
  , 'rois', rois ...
);

%%  Roi file based.

% rois = { 'eyes_nf', 'face', 'mouth', 'left_nonsocial_object_eyes_nf_matched', 'right_nonsocial_object_eyes_nf_matched', 'everywhere' };
rois = 'all';

event_outs = bfw_make_raw_recording_events( ...
    'save', true ...
  , 'is_parallel', true ...
  , 'append', false ...
  , 'skip_existing', false ...
  , 'samples_subdir', 'aligned_raw_samples' ...
  , 'use_bounds_file_for_rois', false ...
  , 'check_accept_mutual_event_func', @bfw.default_check_accept_mutual_event_func ...
  , 'allow_keep_initiating_exclusive_event', false ...
  , 'duration', 70 ...
  , 'rois', rois ...
  , 'main_error_handler', 'error' ...
  , 'keep_output', true ...
  , 'preserve_pre_032821_incorrect_exclusive_event_removal', false ...
  , 'roi_order_func', @bfw.no_mouth_roi_ordering ...
  , 'output_subdir', 'remade_032921' ...
);