intermediate_dirs = {...
    'raw_events' ...
  , 'aligned_raw_samples/position' ...
  , 'aligned_raw_samples/raw_eye_mmv_fixations' ...
  , 'aligned_raw_samples/pupil_size' ...
  , 'aligned_raw_samples/time' ...
  , 'aligned_raw_samples/bounds' ...
  , 'stim' ...
  , 'rois' ...
  , 'single_origin_offsets' ...
  , 'meta' ...
  , 'meta' ...
  , 'plex_start_stop_times' ...
};

filter_files = ...
  @(x) x(contains(x, {'04252022', '04262022', '05022022', '05032022'}));

bfw.copy_intermediates( '~/Desktop/copy_intermediates', intermediate_dirs ...
  , 'config', bfw_st.default_config ...
  , 'filter_files', filter_files ...
  , 'dry_run', false ...
  , 'require_dir', true ...
);