function defaults = bfw_recording_event_defaults(varargin)

defaults = bfw.parsestruct( bfw.make.defaults.raw_events(), {...
    'duration', 10 ...
  , 'fill_gaps', true ...
  , 'fill_gaps_duration', 150 ...
  , 'samples_subdir', 'aligned_binned_raw_samples' ...
  , 'fixations_subdir', 'raw_eye_mmv_fixations' ...
  , varargin{:} ...
});

end