function bfw_make_raw_stimulation_events(varargin)

% use arduino-fixation detection for stimulation days.
bfw.make_raw_events( ...
    'duration', 10 ...
  , 'fill_gaps', true ...
  , 'fill_gaps_duration', 150 ...
  , 'samples_subdir', 'aligned_binned_raw_samples' ...
  , 'fixations_subdir', 'arduino_fixations' ...
  , varargin{:} ...
);

end