conf = bfw.config.load();

[spikedat, spikelabs] = bfw_get_corrected_spike_dat( 'config', conf );

%%

unit_ids = { '129', '137', '207', '259', '238', '261', '518', '560', '575' ...
  , '654', '717', '721', '756', '251', '252', '253', '259', '780' ...
  , '217', '762', '763', '764', '765', '766', '767', '771' };

rest_ids = arrayfun( @num2str, 772:800, 'un', 0 );

unit_ids = csunion( unit_ids, rest_ids );

% unit_ids = { '217' };

unit_id_names = cellfun( @(x) sprintf('unit_uuid__%s', x), unit_ids, 'un', 0 );

mask = fcat.mask( spikelabs ...
  , @find, unit_id_names ...
);

bfw_plot_single_unit_event_trace( spikedat, spikelabs ...
  , 'mask', mask ...
  , 'bin_size', 1 ...
  , 'marker_size', 15 ...
  , 'look_back', 0 ...
  , 'look_ahead', 350 ...
  , 'xlim', [] ...
  , 'use_binned_events', false ...
  , 'event_resolution', 1e-3 ...
  , 'y_shift_fraction', 0 ...
  , 'events_subdir', 'raw_events' ...
  , 'event_selectors', {'eyes_nf'} ...
  , 'custom_color', false ...
  , 'save', true ...
  , 'save_p', fullfile(bfw.dataroot, 'plots', 'spike', dsp3.datedir, 't1') ...
);

