function defaults = bfw_stimulation_event_defaults(varargin)

defaults = bfw.parsestruct( bfw.make.defaults.raw_events(), {...
    'duration', 10 ...
  , 'fill_gaps', true ...
  , 'fill_gaps_duration', 150 ...
  , 'samples_subdir', 'aligned_binned_raw_samples' ...
  , 'fixations_subdir', 'raw_arduino_fixations' ...
  , 'is_truly_exclusive', false ...
  , 'roi_order_func', @bfw.default_stim_task_roi_ordering ...
  , varargin{:} ...
});

end