repadd granger;

parpool( feature('NumCores') );

look_outputs = bfw_make_looking_vector( ...
  'rois', 'face' ...
  , 'files_containing', {'2019_'} ...
);

bfw_run_behavioral_granger( ...
  'look_outputs', look_outputs ...
  , 'prefix', 'permutation_test' ...
  , 'do_save', true ...
);