function out = bfw_gather_aligned_spikes(varargin)

out = bfw_gather_spikes_and_rng( ...
    'spike_func', 'spike_counts' ...
  , 'look_back', -1 ...
  , 'look_ahead', 1 ...
  , 'window_size', 0.05 ...
  , 'step_size', 0.05 ...
  , 'rois', {'eyes_nf', 'face', 'right_nonsocial_object'} ...
  , 'spike_dir', 'cc_spikes' ...
  , 'events_subdir', 'raw_events' ...
  , 'is_already_non_overlapping', true ...
  , 'collapse_nonsocial_object_rois', false ...
  , 'include_rng', false ...
  , varargin{:} ...
);

end