function bfw_run_roi_pair_spike_lda()

conf = bfw.config.load();

lda_out = bfw_roi_pair_spike_lda( ...
    'null_iters', 100 ...
  , 'min_t', 0 ...
  , 'max_t', 400 ...
  , 'rois', {'eyes_nf', 'face', 'everywhere'} ...
  , 'is_parallel', true ...
  , 'config', conf ...
);

save_p = fullfile( bfw.dataroot(conf), 'analyses', 'spike_lda', dsp3.datedir );
shared_utils.io.require_dir( save_p );

save( fullfile(save_p, 'lda_out.mat'), 'lda_out' );

end