% bfw_make_raw_stimulation_events( ...
%     'config', bfw_st.default_config() ...
%   , 'overwrite', false ...
%   , 'samples_subdir', 'aligned_binned_raw_samples' ...
%   , 'fixations_subdir', 'raw_eye_mmv_fixations' ...
% );

%%

% fixations_subdir = 'raw_eye_mmv_fixations';
fixations_subdir = 'raw_arduino_fixations';

bfw_make_raw_stimulation_events( ...
    'config', bfw_st.default_config() ...
  , 'overwrite', false ...
  , 'samples_subdir', 'aligned_raw_samples' ...
  , 'fixations_subdir', fixations_subdir ...
  , 'use_bounds_file_for_rois', false ...
  , 'check_accept_mutual_event_func', @bfw.default_check_accept_mutual_event_func ...
  , 'allow_keep_initiating_exclusive_event', false ...
  , 'duration', 70 ...
  , 'preserve_pre_032821_incorrect_exclusive_event_removal', false ...
  , 'transform_rois', @(rects) bfw.pad_rois(rects, {'eyes_nf'}, 0.1) ...
);