bfw_make_raw_stimulation_events( ...
    'config', bfw_st.default_config() ...
  , 'overwrite', false ...
  , 'samples_subdir', 'aligned_binned_raw_samples' ...
  , 'fixations_subdir', 'raw_eye_mmv_fixations' ...
);