bfw.make_bounds( ...
    'window_size', 500 ...
  , 'step_size', 10 ...
);

%%
bfw.make_events( ...
    'duration', 30 ...  % minimum event duration (ms)
  , 'mutual_method', 'plus-minus' ...   % 'plus-minus' or 'duration' -- whether, for mutual, to allow non-overlapping events
  , 'plus_minus_duration', 10 ... % if method is 'plus-minus', how many ms to allow +/- a true mutual sample
);