function make_psth_for_anova_class(varargin)

bfw_lda.generate_reward_and_gaze_spikes( ...
    'non_eye_face_method', false ...
  , 'spike_dir', 'cc_spikes' ...
  , 'events_subdir', 'raw_events_remade' ...
  , 'include_reward', false ...
  , 'include_rng', false ...
  , 'gaze_rois', make_rois() ...
  , varargin{:} ... 
);  

end

function rois = make_rois()

rois = { 'eyes_nf', 'face', 'left_nonsocial_object', 'right_nonsocial_object' ...
  , 'left_nonsocial_object_eyes_nf_matched', 'right_nonsocial_object_eyes_nf_matched' };

end