function [excl_roi_order, mut_roi_order] = no_mouth_roi_ordering(~)

excl_roi_order = { ....
    'eyes_nf', 'face' ...
  , 'left_nonsocial_object_eyes_nf_matched' ...
  , 'right_nonsocial_object_eyes_nf_matched' ...
  , 'left_nonsocial_object' ...
  , 'right_nonsocial_object' ...
};

mut_roi_order = { 'eyes_nf', 'face' };

end