conf = bfw.config.load();
conf = bfw.set_dataroot( fullfile(conf.PATHS.mount, bfw_image_task_data_root()), conf );

day_info_xls = bfw_it.process_day_info_xls( bfw_it.load_day_info_xls(conf) );
use_files = day_info_xls('date');

% use_days = { '08', '09', '12', '13' };
% use_files = cellfun( @(x) sprintf('06%s2019', x), use_days, 'un', 0 );

common_inputs = struct();
% common_inputs.files_containing = {'04202019', '04222019', '04262019', '04282019', '04302019', '05052019'};
common_inputs.files_containing = use_files;
common_inputs.config = conf;
common_inputs.rect_padding = 0.05;
common_inputs.is_parallel = true;

%%

look_outs = bfw_check_image_task_stim_looking( ...
    'look_ahead', 5e3 ...
  , 'look_back', -150 ...
  , 'bin_size', 100 ...
  , 'bin_func', @pnz ...
  , common_inputs ...
);

%%

fix_outs = bfw_image_task_stim_fixations( ...
    'look_ahead', 5e3 ...
  , 'use_image_offset', true ...
  , common_inputs ...
);

%%

bounds = look_outs.bounds;
t_series = look_outs.t / 1e3;
rel_starts = look_outs.relative_start_times;
labels = look_outs.labels';

bfw_it.plot_decay_timecourse_over_time( bounds, t_series, rel_starts, labels ...
  , 'do_save', false ...
  , 'config', common_inputs.config ...
);

%%

bfw_it.plot_fix_info_over_time( fix_outs ...
  , 'do_save', true ...
  , 'config', common_inputs.config ...
);